### PR TITLE
[PORT] Mild Blood Rites QoL and Blood Halberd cleanup + sprites

### PR DESCRIPTION
**Pull request by 1393F**
## About The Pull Request
https://github.com/tgstation/tgstation/pull/56924

## Why It's Good For The Game
better sprite?

## Changelog
:cl:
tweak: Blood Rites now uses a radial menu to choose which spell to cast.
imageadd: A new sprite for the Bloody Halberds. It looks more like a polearm.
/:cl:

### CODE REVIEW

**Comment by Kitsunemitsu** [comment]
Looks good, needs a 20 minute TM for testing

**Comment by thevandie** [comment]
"needs 20 minute tm for testing"
11 days later

**Comment by Kitsunemitsu** [comment]
It conflicted with the sprite changes

**Comment by BlackCat-055** [comment]
Tested it, looks good, merging

**Pull request merged**
