### PR TITLE
[TG PORT] Adds some new (proper) tables. Also fixes the old reinforced glass table just making a regular metal table bug for the alloys included.

### PR DESCRIPTION
**Pull request by bruhlookatthisdood**
# PORT OF TG #61153

## About The Pull Request

Added five new tables based on pre-existing sprites. Alien tables were used as the base for the reinforced glass variants since that's the only example of a reinforced glass table in the codebase, and I didn't want to just make them regular glass tables with a fancier finish. Now that the materals included have proper tables instead of relying on the materials system, you won't get a standard metal table that eats your metal sheet when you try to make them.

## Why It's Good For The Game

More tables

## Changelog

🆑
add: Added five new table variants - Plasmaglass, Reinforced Plasmaglass, Reinforced Glass, Plastitanium Glass, and Titaniumglass.
fix: Attempting to create a table with the aforementioned materials will no longer result in a normal metal table.
/🆑

### CODE REVIEW

**Comment by bruhlookatthisdood** [comment]
image

**Comment by DaddyIssues98** [comment]
do this broke table flip?

**Comment by DaddyIssues98** [comment]
i dont like that this will make like half of the tables not flipping, is weird

**Comment by bruhlookatthisdood** [comment]
> i dont like that this will make like half of the tables not flipping, is weird

l;ets just say that uhhhh
they are bolted to the floor

**Pull request merged**
